### ISSUE TITLE
User can delete a saved event

### ISSUE THREAD

**Issue by dnypham** [dnypham/eventinerary#6]
## ⚙️ Feature

User can delete a saved event.

## 📐 Functionality

User can select a saved event and delete it from the database.

## 🖼️ Wireframes

<img width="940" alt="Screen Shot 2021-12-28 at 10 36 38 AM" src="https://user-images.githubusercontent.com/85265067/147592330-ca5c255a-f349-4a45-8ebe-ac224d59279c.png">
<img width="939" alt="Screen Shot 2021-12-28 at 10 36 53 AM" src="https://user-images.githubusercontent.com/85265067/147592337-4a3f57d8-fd74-4805-bb17-56ab7edebffd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a delete request from the client.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a "delete event" button that appears when a saved event is selected.
- [x] Create a modal confirming if they want to delete an event.
- [x] Send a request from the client to the server with the eventId to delete it from the database.

### 🧑‍⚕️ Clean Up

- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
